""" Guis_done_hard_ui.py --

 UI generated by GUI Builder Build 146 on 2010-07-14 22:23:30 from:
    /home/steve/Desktop/Guis_done_hard.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Pmw
import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Guis_done_hard(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):
        self._images.append(Tkinter.PhotoImage('/home/steve/Desktop/steve-pres/flickr_logo_gamma.gif.v59899.14.gif', file = '/home/steve/Desktop/steve-pres/flickr_logo_gamma.gif.v59899.14.gif'))


        # Widget Initialization
        self._frame_1 = Tkinter.Frame(root,
        )
        self._labelframe_1 = Tkinter.LabelFrame(root,
            text = "_labelframe_1",
        )
        self._button_1 = Tkinter.Button(root,
            text = "_button_1",
        )
        self._button_2 = Tkinter.Button(root,
            text = "_button_2",
        )
        self._button_3 = Tkinter.Button(root,
            image = "/home/steve/Desktop/steve-pres/flickr_logo_gamma.gif.v59899.14.gif",
            text = "_button_3",
        )
        self._label_1 = Tkinter.Label(self._labelframe_1,
            text = "_label_1",
        )
        self._NoteBook_1 = Pmw.NoteBook(root,
        )
        self._TimeCounter_1 = Pmw.TimeCounter(root,
        )
        self._Counter_1 = Pmw.Counter(root,
        )
        self._ComboBox_1 = Pmw.ComboBox(root,
        )
        self._radiobutton_1 = Tkinter.Radiobutton(root,
            text = "_radiobutton_1",
        )
        self._radiobutton_2 = Tkinter.Radiobutton(root,
            text = "_radiobutton_2",
        )
        self._label_2 = Tkinter.Label(root,
            text = "_label_2",
        )

        # widget commands

        self._button_1.configure(
            command = self._button_1_command
        )
        self._button_2.configure(
            command = self._button_2_command
        )
        self._button_3.configure(
            command = self._button_3_command
        )
        self._NoteBook_1.configure(
            createcommand = self.None
        )
        self._NoteBook_1.configure(
            lowercommand = self.None
        )
        self._NoteBook_1.configure(
            raisecommand = self.None
        )
        self._TimeCounter_1.configure(
            command = self.None
        )
        self._ComboBox_1.configure(
            selectioncommand = self.None
        )
        self._radiobutton_1.configure(
            command = self._radiobutton_1_command
        )
        self._radiobutton_2.configure(
            command = self._radiobutton_2_command
        )


        # Geometry Management
        self._frame_1.grid(
            in_    = root,
            column = 2,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._labelframe_1.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._button_1.grid(
            in_    = root,
            column = 2,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_2.grid(
            in_    = root,
            column = 1,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_3.grid(
            in_    = root,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_1.grid(
            in_    = self._labelframe_1,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._NoteBook_1.grid(
            in_    = root,
            column = 2,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._TimeCounter_1.grid(
            in_    = root,
            column = 2,
            row    = 5,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._Counter_1.grid(
            in_    = root,
            column = 2,
            row    = 6,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._ComboBox_1.grid(
            in_    = root,
            column = 2,
            row    = 7,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._radiobutton_1.grid(
            in_    = root,
            column = 1,
            row    = 8,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._radiobutton_2.grid(
            in_    = root,
            column = 1,
            row    = 7,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_2.grid(
            in_    = root,
            column = 1,
            row    = 6,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 313, pad = 0)
        root.grid_rowconfigure(3, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(4, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(5, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(6, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(7, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(8, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 163, pad = 0)
        root.grid_columnconfigure(2, weight = 0, minsize = 970, pad = 0)
        self._labelframe_1.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._labelframe_1.grid_columnconfigure(1, weight = 0, minsize = 2, pad = 0)


