""" main_connected_ui.py --

 UI generated by GUI Builder Build 146 on 2010-07-26 17:23:46 from:
    /home/steve/Desktop/code/visual-secure/gui/main_connected.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Main_connected(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._label_1 = Tkinter.Label(root,
            text = "Currently connected to:",
        )
        self._label_2 = Tkinter.Label(root,
            text = "...",
        )
        self._checkbutton_1 = Tkinter.Checkbutton(root,
            justify = "left",
            text = "Read SMS",
        )
        self._checkbutton_2 = Tkinter.Checkbutton(root,
            text = "Receive Phonebook",
        )
        self._checkbutton_3 = Tkinter.Checkbutton(root,
            text = "Send SMS",
        )
        self._button_1 = Tkinter.Button(root,
            text = "Execute",
        )
        self._checkbutton_4 = Tkinter.Checkbutton(root,
            text = "Call Number",
        )
        self._label_3 = Tkinter.Label(root,
            text = "Quick fun",
        )
        self._button_2 = Tkinter.Button(root,
            text = "Let Phone Ring",
        )
        self._button_3 = Tkinter.Button(root,
            text = "Reset Clock",
        )
        self._label_4 = Tkinter.Label(root,
            font = "helvetica 9 bold",
            justify = "right",
            text = "Status:",
        )
        self._label_5 = Tkinter.Label(root,
            text = "...",
        )
        self._button_4 = Tkinter.Button(root,
            text = "Quick overview",
        )
        self._text_1 = Tkinter.Text(root,
            height = 0,
            width = 0,
        )
        self._button_5 = Tkinter.Button(root,
            text = "Add alarm",
        )
        self._checkbutton_5 = Tkinter.Checkbutton(root,
            text = "Enable Caller ID",
        )
        self._button_6 = Tkinter.Button(root,
            text = "Play Music",
        )
        self._text_2 = Tkinter.Text(root,
            height = 0,
            width = 0,
        )
        self.menu = Tkinter.Menu(root,
        )

        # widget commands

        self._checkbutton_1.configure(
            command = self._checkbutton_1_command
        )
        self._checkbutton_2.configure(
            command = self._checkbutton_2_command
        )
        self._checkbutton_3.configure(
            command = self._checkbutton_3_command
        )
        self._button_1.configure(
            command = self._button_1_command
        )
        self._checkbutton_4.configure(
            command = self._checkbutton_4_command
        )
        self._button_2.configure(
            command = self._button_2_command
        )
        self._button_3.configure(
            command = self._button_3_command
        )
        self._button_4.configure(
            command = self._button_4_command
        )
        self._text_1.configure(
            xscrollcommand = self._text_1_xscrollcommand
        )
        self._text_1.configure(
            yscrollcommand = self._text_1_yscrollcommand
        )
        self._button_5.configure(
            command = self._button_5_command
        )
        self._checkbutton_5.configure(
            command = self._checkbutton_5_command
        )
        self._button_6.configure(
            command = self._button_6_command
        )
        self._text_2.configure(
            xscrollcommand = self._text_2_xscrollcommand
        )
        self._text_2.configure(
            yscrollcommand = self._text_2_yscrollcommand
        )
        self.menuitem1 = Tkinter.Menu(self.menu,
            tearoff = 0,
        )
        self.menu.add_cascade(
            label = "Back to devices",
            menu = self.menuitem1,
        )
        self.menuitem2 = Tkinter.Menu(self.menu,
            tearoff = 0,
        )
        self.menu.add_cascade(
            label = "Kill program",
            menu = self.menuitem2,
        )


        # Geometry Management
        self._label_1.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_2.grid(
            in_    = root,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._checkbutton_1.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "w"
        )
        self._checkbutton_2.grid(
            in_    = root,
            column = 1,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "w"
        )
        self._checkbutton_3.grid(
            in_    = root,
            column = 1,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "w"
        )
        self._button_1.grid(
            in_    = root,
            column = 2,
            row    = 13,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._checkbutton_4.grid(
            in_    = root,
            column = 1,
            row    = 6,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "w"
        )
        self._label_3.grid(
            in_    = root,
            column = 1,
            row    = 7,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "sw"
        )
        self._button_2.grid(
            in_    = root,
            column = 1,
            row    = 8,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ew"
        )
        self._button_3.grid(
            in_    = root,
            column = 1,
            row    = 10,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ew"
        )
        self._label_4.grid(
            in_    = root,
            column = 1,
            row    = 14,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "e"
        )
        self._label_5.grid(
            in_    = root,
            column = 2,
            row    = 14,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_4.grid(
            in_    = root,
            column = 1,
            row    = 12,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ew"
        )
        self._text_1.grid(
            in_    = root,
            column = 1,
            row    = 13,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._button_5.grid(
            in_    = root,
            column = 1,
            row    = 11,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ew"
        )
        self._checkbutton_5.grid(
            in_    = root,
            column = 1,
            row    = 5,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "w"
        )
        self._button_6.grid(
            in_    = root,
            column = 1,
            row    = 9,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ew"
        )
        self._text_2.grid(
            in_    = root,
            column = 3,
            row    = 7,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 6, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 17, pad = 0)
        root.grid_rowconfigure(3, weight = 0, minsize = 6, pad = 0)
        root.grid_rowconfigure(4, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(5, weight = 0, minsize = 7, pad = 0)
        root.grid_rowconfigure(6, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(7, weight = 1, minsize = 51, pad = 0)
        root.grid_rowconfigure(8, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(9, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(10, weight = 0, minsize = 12, pad = 0)
        root.grid_rowconfigure(11, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(12, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(13, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(14, weight = 0, minsize = 2, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(2, weight = 1, minsize = 40, pad = 0)
        root.grid_columnconfigure(3, weight = 1, minsize = 40, pad = 0)
        root.configure(menu = self.menu)


