#!/usr/bin/env python
""" main_scan.py --

 UI generated by GUI Builder Build 146 on 2010-07-26 16:40:40 from:
    /home/steve/Desktop/code/visual-secure/gui/main_scan.ui
 This file is auto-generated.  Only the code within
    '# BEGIN USER CODE (global|class)'
    '# END USER CODE (global|class)'
 and code inside the callback subroutines will be round-tripped.
 The 'main' function is reserved.
"""

from Tkinter import *
from main_scan_ui import Main_scan

# BEGIN USER CODE global

# END USER CODE global

class CustomMain_scan(Main_scan):
    pass

    # BEGIN CALLBACK CODE
    # ONLY EDIT CODE INSIDE THE def FUNCTIONS.

    # _button_1_command --
    #
    # Callback to handle _button_1 widget option -command
    def _button_1_command(self, *args):
        pass

    # _listbox_1_xscrollcommand --
    #
    # Callback to handle _listbox_1 widget option -xscrollcommand
    def _listbox_1_xscrollcommand(self, *args):
        pass

    # _listbox_1_yscrollcommand --
    #
    # Callback to handle _listbox_1 widget option -yscrollcommand
    def _listbox_1_yscrollcommand(self, *args):
        pass

    # logo_xscrollcommand --
    #
    # Callback to handle logo widget option -xscrollcommand
    def logo_xscrollcommand(self, *args):
        pass

    # logo_yscrollcommand --
    #
    # Callback to handle logo widget option -yscrollcommand
    def logo_yscrollcommand(self, *args):
        pass

    # END CALLBACK CODE

    # BEGIN USER CODE class

    # END USER CODE class

def main():
    # Standalone Code Initialization
    # DO NOT EDIT
    try: userinit()
    except NameError: pass
    root = Tk()
    demo = CustomMain_scan(root)
    root.title('main_scan')
    try: run()
    except NameError: pass
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__': main()
