""" main_scan_ui.py --

 UI generated by GUI Builder Build 146 on 2010-07-26 16:40:40 from:
    /home/steve/Desktop/code/visual-secure/gui/main_scan.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Main_scan(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._label_1 = Tkinter.Label(root,
            text = "Nearby Bluetooth Devices",
        )
        self._listbox_1 = Tkinter.Listbox(root,
            height = 0,
            width = 0,
        )
        self._button_1 = Tkinter.Button(root,
            text = "Connect",
        )
        self._label_2 = Tkinter.Label(root,
            text = "Status:",
        )
        self.status = Tkinter.Label(root,
            text = "scanning...",
        )
        self.logo = Tkinter.Canvas(root,
            height = 0,
            width = 0,
        )
        self.menu = Tkinter.Menu(root,
        )

        # widget commands

        self._listbox_1.configure(
            xscrollcommand = self._listbox_1_xscrollcommand
        )
        self._listbox_1.configure(
            yscrollcommand = self._listbox_1_yscrollcommand
        )
        self._button_1.configure(
            command = self._button_1_command
        )
        self.logo.configure(
            xscrollcommand = self.logo_xscrollcommand
        )
        self.logo.configure(
            yscrollcommand = self.logo_yscrollcommand
        )
        self.menuitem1 = Tkinter.Menu(self.menu,
            tearoff = 0,
        )
        self.menu.add_cascade(
            label = "Scan",
            menu = self.menuitem1,
        )
        self.menuitem2 = Tkinter.Menu(self.menu,
            tearoff = 0,
        )
        self.menu.add_cascade(
            label = "Exit",
            menu = self.menuitem2,
        )
        self.menuitem3 = Tkinter.Menu(root,
            tearoff = 0,
        )
        self.menuitem2.add_cascade(
            label = "Main Menu",
            menu = self.menuitem3,
        )
        self.menuitem4 = Tkinter.Menu(root,
            tearoff = 0,
        )
        self.menuitem2.add_cascade(
            label = "Kill program",
            menu = self.menuitem4,
        )


        # Geometry Management
        self._label_1.grid(
            in_    = root,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._listbox_1.grid(
            in_    = root,
            column = 2,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._button_1.grid(
            in_    = root,
            column = 3,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_2.grid(
            in_    = root,
            column = 1,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.status.grid(
            in_    = root,
            column = 2,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.logo.grid(
            in_    = root,
            column = 3,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(3, weight = 1, minsize = 144, pad = 0)
        root.grid_rowconfigure(4, weight = 0, minsize = 2, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(2, weight = 1, minsize = 242, pad = 0)
        root.grid_columnconfigure(3, weight = 0, minsize = 2, pad = 0)
        root.configure(menu = self.menu)


