#!/usr/bin/env python
""" main.py --

 UI generated by GUI Builder Build 146 on 2010-07-26 17:21:41 from:
    /home/steve/Desktop/code/visual-secure/gui/main.ui
 This file is auto-generated.  Only the code within
    '# BEGIN USER CODE (global|class)'
    '# END USER CODE (global|class)'
 and code inside the callback subroutines will be round-tripped.
 The 'main' function is reserved.
"""

from Tkinter import *
from main_ui import Main

# BEGIN USER CODE global

# END USER CODE global

class CustomMain(Main):
    pass

    # BEGIN CALLBACK CODE
    # ONLY EDIT CODE INSIDE THE def FUNCTIONS.

    # _button_1_command --
    #
    # Callback to handle _button_1 widget option -command
    def _button_1_command(self, *args):
        pass

    # _button_2_command --
    #
    # Callback to handle _button_2 widget option -command
    def _button_2_command(self, *args):
        pass

    # _button_3_command --
    #
    # Callback to handle _button_3 widget option -command
    def _button_3_command(self, *args):
        pass

    # _button_4_command --
    #
    # Callback to handle _button_4 widget option -command
    def _button_4_command(self, *args):
        pass

    # _button_5_command --
    #
    # Callback to handle _button_5 widget option -command
    def _button_5_command(self, *args):
        pass

    # END CALLBACK CODE

    # BEGIN USER CODE class

    # END USER CODE class

def main():
    # Standalone Code Initialization
    # DO NOT EDIT
    try: userinit()
    except NameError: pass
    root = Tk()
    demo = CustomMain(root)
    root.title('main')
    try: run()
    except NameError: pass
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__': main()
