""" main_ui.py --

 UI generated by GUI Builder Build 146 on 2010-07-26 17:21:40 from:
    /home/steve/Desktop/code/visual-secure/gui/main.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Main(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._button_1 = Tkinter.Button(root,
            text = "Super Bluetooth",
        )
        self._button_2 = Tkinter.Button(root,
            text = "Password Cracker",
        )
        self._button_3 = Tkinter.Button(root,
            text = "Password Test",
        )
        self._button_4 = Tkinter.Button(root,
            text = "Facebook Attack",
        )
        self._button_5 = Tkinter.Button(root,
            text = "Advanced Test Suite",
        )

        # widget commands

        self._button_1.configure(
            command = self._button_1_command
        )
        self._button_2.configure(
            command = self._button_2_command
        )
        self._button_3.configure(
            command = self._button_3_command
        )
        self._button_4.configure(
            command = self._button_4_command
        )
        self._button_5.configure(
            command = self._button_5_command
        )


        # Geometry Management
        self._button_1.grid(
            in_    = root,
            column = 2,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ew"
        )
        self._button_2.grid(
            in_    = root,
            column = 3,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ew"
        )
        self._button_3.grid(
            in_    = root,
            column = 2,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ew"
        )
        self._button_4.grid(
            in_    = root,
            column = 3,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ew"
        )
        self._button_5.grid(
            in_    = root,
            column = 2,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ew"
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(3, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(4, weight = 0, minsize = 17, pad = 0)
        root.grid_rowconfigure(5, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(2, weight = 0, minsize = 2, pad = 0)
        root.grid_columnconfigure(3, weight = 0, minsize = 11, pad = 0)
        root.grid_columnconfigure(4, weight = 0, minsize = 40, pad = 0)


