""" Slider_test_ui.py --

 UI generated by GUI Builder Build 146 on 2010-06-02 16:18:57 from:
    /home/steve/Desktop/code/visual-secure/py-ws/Slider_test.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Slider_test(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):
        self.variomat = Tkinter.StringVar(root)


        # Widget Initialization
        self._scale_1 = Tkinter.Scale(root,
        )
        self._label_1 = Tkinter.Label(root,
            text = "OhYeah",
            textvariable = self.variomat,
        )

        # widget commands

        self._scale_1.configure(
            command = self._scale_1_command
        )


        # Geometry Management
        self._scale_1.grid(
            in_    = root,
            column = 2,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ns"
        )
        self._label_1.grid(
            in_    = root,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(2, weight = 1, minsize = 267, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(2, weight = 0, minsize = 475, pad = 0)


