#!/usr/bin/env python""" Slider_test.py --

"""
 UI generated by GUI Builder Build 146 on 2010-06-02 16:19:02 from:
    /home/steve/Desktop/code/visual-secure/py-ws/Slider_test.ui
 This file is auto-generated.  Only the code within
    '# BEGIN USER CODE (global|class)'
    '# END USER CODE (global|class)'
 and code inside the callback subroutines will be round-tripped.
 The 'main' function is reserved.
"""

from Tkinter import *
from Slider_test_ui import Slider_test

# BEGIN USER CODE global

# END USER CODE global

class CustomSlider_test(Slider_test):
    pass

    # BEGIN CALLBACK CODE
    # ONLY EDIT CODE INSIDE THE def FUNCTIONS.

    # _scale_1_command --
    #
    # Callback to handle _scale_1 widget option -command
    def _scale_1_command(self, *args):
        pass

    # END CALLBACK CODE

    # BEGIN USER CODE class

    # END USER CODE class

def main():
    # Standalone Code Initialization
    # DO NOT EDIT
    try: userinit()
    except NameError: pass
    root = Tk()
    demo = CustomSlider_test(root)
    root.title('Slider_test')
    try: run()
    except NameError: pass
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__': main()
